name: Documentation Improvement
description: Suggest improvements or fixes for documentation
title: "[Docs]: "
labels: ["documentation", "good first issue"]
body:
  - type: textarea
    attributes:
      label: Description
      description: Clearly describe what needs to be improved
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Changes
      description: Explain how you plan to improve it
    validations:
      required: true
